parameters:
- name: buildPool
  type: string
  default: 'ubuntu-20.04'
- name: terraformFolders
  type: object
  default:
   - cde-backend
   - cde-frontend
   - cde-shared
- name: terraformVersion
  type: string
  default: "0.15.0"

jobs:
- job: Validate
  pool:
    vmImage: ${{ parameters.buildPool }}

  steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: ${{ parameters.terraformVersion }}

    - ${{ each terraformFolder in parameters.terraformFolders }}:

      - script: |
          terraform -chdir=${{ parameters.terraformFolder }} init -backend=false
        displayName: Terraform init

      - script: |
          terraform -chdir=${{ parameters.terraformFolder }} validate
        displayName: Terraform validate
    # - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
    #   displayName: 'TF Validate'
    #   inputs:
    #     command: validate
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.terraformFolder }}'