parameters:
- name: buildPool
  type: string
  default: 'ubuntu-20.04'
- name: terraformFolders
  type: object
  default:
   - 'docs'
   - 'enviroment'
   - 'modules'
  # default:
  #  - 'cde-backend'
  #  - 'cde-frontend'
  #  - 'cde-shared'
- name: terraformVersion
  type: string
  default: "1.4.6"

jobs:
- job: Validate
  pool:
    vmImage: ${{ parameters.buildPool }}

  steps:
    # - task: TerraformInstaller@0
    #   displayName: Install Terraform
    #   inputs:
    #     terraformVersion: ${{ parameters.terraformVersion }}
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install TF ${{ parameters.terraformVersion }}'
      inputs:
        terraformVersion: ${{ parameters.terraformVersion }}

    - ${{ each terraformFolder in parameters.terraformFolders }}:

      # - script: |
      #     terraform -chdir=${{ terraformFolder }} init -backend=false
      #   displayName: Terraform init

      # - script: |
      #     terraform -chdir=${{ terraformFolder }} validate
      #   displayName: Terraform validate
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
        displayName: 'TF Validate'
        inputs:
          command: validate
          workingDirectory: '$(System.DefaultWorkingDirectory)/${{ terraformFolder }}'