version: '3.8'

services:
  ecobites-db:
    image: "${ecr_registry}/ecobites-db-image:${image_tag}"
    environment:
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"
    networks:
      - ecobites-network
    volumes:
      - db_data:/var/lib/postgresql/data

  ecobites-backend:
    image: "${ecr_registry}/ecobites-backend-image:${image_tag}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ecobites-db:5432/${db_name}
      SPRING_DATASOURCE_USERNAME: ${db_username}
      SPRING_DATASOURCE_PASSWORD: ${db_password}
    ports:
      - "8081:8081"
    networks:
      - ecobites-network
    depends_on:
      - ecobites-db

volumes:
  db_data:

networks:
  ecobites-network:
    driver: bridge