version: '3.9'

services:
  db:
    image: mikudpua/music_app:${BUILD_NUMBER}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_P0RT=6379
      - REDIS_HOST=redis://redis:6379
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@${POSTGRES_HOST}
      - SECRET_KEY_BASE=017452ae8e51337d910567147688e0e930af461f8201a4ac40d3e40b7cfce675b031009b53de1a2fdd106f2fd16d975f147c4e10986f505ca4189da2cd573cc4
    ports:
      - 3000:3000
    networks:
      - mynetwork
  redis:
    image: redis:7-alpine
    ports:
    - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

volumes:
  redis_data:

networks:
  mynetwork:
    driver: bridge