name: Infra Ecobytes

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      action:
        description: "Create or destroy infrastructure"
        required: true
        type: choice
        options:
          - create
          - destroy
      environment:
        description: "Chose infrastructure environment to be created"
        required: true
        type: choice
        options:
          - dev
          # - prod

permissions:
  id-token: write
  contents: read

jobs:
  install-infra:
    if: github.event.inputs.action == 'create' || github.event_name == 'push' || github.event_name == 'pull_request'
    uses: ./.github/workflows/infra-create.yaml

  uninstall-infra:
    if: github.event.inputs.action == 'destroy'
    uses: ./.github/workflows/infra-destroy.yaml