name: Infra Ecobytes

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      action:
        description: "Create or destroy infrastructure"
        required: true
        type: choice
        options:
          - create
          - destroy
          - build_backend
          - deploy_backend
          - build_frontend
          - deploy_frontend
      # deploy-backend:
      #   description: "Deploy backend"
      #   required: false
      #   type: boolean
      # deploy-frontend:
      #   description: "Deploy frontend"
      #   required: false
      #   type: boolean
      environment:
        description: "Chose infrastructure environment to be created"
        required: true
        type: choice
        options:
          - dev
          # - prod    

permissions:
  id-token: write
  contents: read

jobs:
  install-infra:
    if: github.event.inputs.action == 'create' || github.event_name == 'push' || github.event_name == 'pull_request'
    uses: ./.github/workflows/infra-create.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      trigger_event: ${{ github.event.inputs.action }}

  uninstall-infra:
    if: github.event.inputs.action == 'destroy'
    uses: ./.github/workflows/infra-destroy.yaml

  build-backend:
    if: github.event.inputs.action == 'build_backend' || github.event.inputs.action == 'deploy_backend'
    uses: marinaimeninnik/eco-bites-back/.github/workflows/gradle.yml@docker-compose
    with:
      environment: ${{ github.event.inputs.environment }}
      # trigger_event: ${{ github.event_name }}
  
  deliver-backend:
    if: github.event.inputs.action == 'deploy_backend'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Install Infra
      # needs: build-backend
      uses: marinaimeninnik/eco-bites-infra/.github/workflows/infra-create.yaml@frontend_deployment
      # permissions:
      #   id-token: write
      #   contents: read
      with:
        environment: ${{ github.event.inputs.environment }}
        # trigger_pipeline: ${{ github.workflow }}
        trigger_event: ${{ github.event.inputs.action }}

    - name: Deploy Backend
      uses: marinaimeninnik/eco-bites-back/.github/workflows/docker-deploy.yaml@docker-compose
      
  
  # deploy-backend:
  #   if: github.event.inputs.action == 'deploy_backend'
  #   needs: deliver-backend
  #   uses: marinaimeninnik/eco-bites-back/.github/workflows/docker-deploy.yaml@docker-compose
  #   permissions:
  #     id-token: write
  #     contents: read




  # deploy-frontend:
  #   if: github.event.inputs.deploy-frontend == true
  #   uses: marinaimeninnik/eco-bites-front/.github/workflows/react.yaml@CI-CD_pipeline
  #   # with:
  #   #   environment: ${{ github.event.inputs.environment }}
  #   #   trigger_pipeline: ${{ github.workflow }}